### ISSUE TITLE
installation under debian linux

### ISSUE THREAD

**Issue by jordancurve** [draffensperger/golp#4]
Might be good to note in the docs that golp works great under Debian 8 if you delete the two "#cgo linux" lines and run:

sudo apt-get install liblpsolve55-dev

**Comment by draffensperger** [comment]
Good to know! I'll plan to update the docs accordingly.

**Comment by draffensperger** [comment]
I just added a note to this effect in the Readme: https://github.com/draffensperger/golp#installation . It's a first pass approach to this as people would still need to modify the `#cgo` pragma. Potentially in the future we could make it so that on Linux it will look for the library in either the general library path or the local `lpsolve` folder.

I'm going to close this for now, but if this is something someone else runs into and would like a more general approach feel free to ask for it or propose a way to do it in a pull request.
